http:
  port: "8081"
  
db:
  config:
    host: "localhost"
    port: "3306"
    user: "root"
    password: "root"
    database: "bfs"

query:
  select: "select * from Bank_Transactions"
  
deployment:
  app:
    runtime: "4.4.0"
  region: "us-east-2"
  workers:  "1"
  workerType: "MICRO"